baseurl = "https://smuth.me/"
languageCode = "en-us"
title = "cat /dev/null > /proc/mind"
theme = "terminal"

[params]
subtitle = "Ain't the brightest bit in the byte."
github = "https://github.com/smuth4"
googleAnalytics = "UA-80421871-1"
analytics = "UA-80421871-1"
showRSS = true
languageCode = "en"
contentTypeName = "posts"
themeColor = "blue"
centerTheme = true

[languages]
  [languages.en]
    title = "cat /dev/null > /proc/mind"
    subtitle = "Ain't the brightest bit in the byte."
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    [languages.en.params.logo]
      logoText = "cat /dev/null > /proc/mind"
      logoHomeLink = "/"
    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "github"
        name = "Github"
        url = "https://github.com/smuth4"
