baseurl = "https://smuth.me/"
languageCode = "en-us"
title = "cat /dev/null > /proc/mind"
theme = "angels-ladder"

[Params]
subtitle = "Ain't the brightest bit in the byte."
github = "https://github.com/smuth4"
googleAnalytics = "UA-80421871-1"
analytics = "UA-80421871-1"
